project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Mini Projects"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: true
    